spring:
  main:
    web-application-type: none
    banner-mode: off
logging:
  level:
    root: off
kdr:
  master:
    master-server-host: localhost
    master-server-port: 8080
    master-server-scheme: http